# Identification de l'application (pour les logs)
spring.application.name=enipathfinal

# Serveur
server.port=8081

# Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/enipath
spring.datasource.username=root
spring.datasource.password=marwa1405

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Astuce : tu peux supprimer la ligne suivante, Hibernate détecte MySQL automatiquement
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Upload de fichiers
app.upload.dir=uploads/cours
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB